### ISSUE TITLE
Gimp

### ISSUE THREAD

**Issue by aoloe** [libregraphicsmeeting/state-of-lg-2018#4]
schumaml asks mitch...

**Comment by prokoudine** [comment]
![gimp-0](https://user-images.githubusercontent.com/57467/39216130-2dfd0962-4823-11e8-91ea-999fc9516187.png)
![gimp-1](https://user-images.githubusercontent.com/57467/39216131-2e338fb4-4823-11e8-9e75-9d3be92b0de9.png)
![gimp-2](https://user-images.githubusercontent.com/57467/39216132-2e5aa1d0-4823-11e8-8074-4dcd14ab2088.png)

I'll write some text for you, too :)

**Comment by aoloe** [comment]
some more text? i thought the slides should have been as visual as possible : - )

**Comment by prokoudine** [comment]
Yeah, I got a little overexcited. Can't think of anything better to fit into 2-3 slides right now, let's see if the rest of the team can come up with something more visual.

**Comment by aoloe** [comment]
well, if you find something visual, then you have 90% of your text : - )

**Comment by patdavid** [comment]
I took a quick pass at this, please hack at it as needed.
![gimp-slide0](https://user-images.githubusercontent.com/2778928/39259623-82a4e526-487c-11e8-9237-7eec1c7b6b4f.png)
![gimp-slide1](https://user-images.githubusercontent.com/2778928/39259626-86ca15ae-487c-11e8-8adf-690d5bc5ba63.png)
![gimp-slide2](https://user-images.githubusercontent.com/2778928/39259630-88bb2614-487c-11e8-9d24-b6a58fef2cbc.png)

Source .svg if anyone wants to edit (You'll need League Gothic and Ostrich from League of Moveable Type: https://www.theleagueofmoveabletype.com/):


[2018LGMStateOf.zip](https://github.com/libregraphicsmeeting/state-of-lg-2018/files/1947954/2018LGMStateOf.zip)

**Comment by aoloe** [comment]
well done!

@patdavid so should i take your  slides and use prokoudine's one as the gimp.txt file?

**Comment by aoloe** [comment]
ok, i'll add pat's slides to the repository.

**Comment by aoloe** [comment]
ok, it's done.
slides in, old slides as speakers notes.

the talk is close so, i close this ticket.
