### ISSUE TITLE
Projects to be contacted

### ISSUE THREAD

**Issue by aoloe** [libregraphicsmeeting/state-of-lg-2018#5]
Please comment on this issue to get us to add new project that should be contacted!

Fonts:
- [ ] [Font Baker](https://fontbakery.com)
- [ ] Fontforge
- [ ] Font Validator (create list)
- [ ] [Freetype](https://freetype.org)
- [ ] Google Fonts (dave, lgm list)
- [ ] Metapolator
- [ ] [Oert](https://www.oert.org)
- [ ] Openfonts

Bitmap/Photo editing / drawing / management:
- [ ] Darktable
- [x] Gegl (lgm mailing list; asked pippin on #lgm)
- [x] Gimp (lgm irc channel)
- [x] G'mic ([asked](https://discuss.pixls.us/t/slides-for-the-state-of-libre-graphics-2018/7405) in the forums)
- [ ] Krita (boud, lgm list)
- [x] Mypaint ([asked](https://community.mypaint.org/t/slides-for-the-state-of-libre-graphics-2018/1198) in the [forum](https://community.mypaint.org/))
- [x] [Pixls.us](https://pixls.us) ([asked](https://discuss.pixls.us/t/project-slides-for-the-state-of-libre-graphics-2018/7406) in the forums)

Vector drawing:

- [x] Inkscape (inkscape irc channel)
- [ ] [Openclipart](https://openclipart.org) (mailed love@openclipart.org)

DTP / Publishing
- [x] Laidout (tom, lgm list?)
- [ ] Open source publishing (lgm mailing list?)
- [x] Scribus (mail an Scribus mailing list)

Colors:

- [ ] [ColorHug](https://hughski.com/)
- [x] Freie Farbe (mail an Christoph Schäfer)

3D

- [ ] Blender

Video

- [ ] Kdenlive
- [ ] Morevna
- [ ] Synfig Studio

Resources (manuals, collections, ...)

- [ ] Flossmanuals (mailinglist?)
- [ ] Flossmanuals-francophone (elisa?)
- [ ] Libre Graphics Magazine

Other:

- [ ] [UpStage](http://upstage.org.nz)
- [ ] Valentina project

**Comment by ghost** [comment]
Bitmap/Photo editing / drawing / management:

- [ ] [AzPainter 2.x](https://github.com/symbian9/azpainter) - for Unix-like systems

Vector drawing:

- [ ] [sK1 2.0 + UniConverter 2.0](https://github.com/sk1project/sk1-wx)

DTP / Publishing

- [ ] [OpenOrienteering Mapper](https://github.com/openorienteering/mapper)
- [ ] [gLabels 4.0](https://github.com/jimevins/glabels-qt)

3D

- [ ] [Stellarium](https://github.com/stellarium/stellarium)
- [ ] [LeoCAD](https://github.com/leozide/leocad)
- [ ] [SolveSpace](https://github.com/solvespace/solvespace)

Video

- [ ] [VidCutter](https://github.com/ozmartian/vidcutter)

Other:

- [ ] [PatternPaint](https://github.com/blinkinlabs/patternpaint)
- [ ] [Tiled](https://github.com/bjorn/tiled)

**Comment by ghost** [comment]
> Other
> 
> - [ ] Valentina project

There was drama with *Valentina Project*

- http://libregraphicsworld.org/blog/entry/valentina-seamly2d

So you should contact with *Roman Telezhinsky* (aka @dismine )

- https://bitbucket.org/dismine/valentina

**Comment by aoloe** [comment]
sad to read that... but -- also sadly -- the state of LG has already taken place for this year... i only could directly contact a few projects and I had to rely on the mouth to mouth propaganda for the other one...

**Comment by dismine** [comment]
> Please comment on this issue to get us to add new project that should be contacted!

Why do you want to contact?

**Comment by aoloe** [comment]
@dismine the libre graphics meeting is a yearly meeting for the developers, users and people that otherwise relate to grahpics with free software.

the first talk of the meeting is a "state of libre graphics" where we present what has happened during the last year and what are the plans for the next year.

for that, we need the projects to submit three slides and the speakers notes.

and in order to get the projects to know that they can / should submit the slides we need to have a list of projects to contact.

**Comment by aoloe** [comment]
i've created [a ticket for 2019](https://github.com/libregraphicsmeeting/state-of-lg-2019/issues/1) and added @Symbian9 suggestions to it.

let's have the discussion continue there.
